version: '3.8'

services:
  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/src:/app/src
      - ./data:/app/data
    container_name: gsrvs-backend
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    container_name: gsrvs-frontend
    depends_on:
      - backend
